import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AppSideBar  from "./components/AppSideBar";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "@/components/ui/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { CoursesProvider } from "@/lib/courses-context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export  default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore =  await cookies();
  const defaultOpen = cookiesStore.get("sidebar-open")?.value === "true" ? true : false;
  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppSideBar />
           <CoursesProvider>
          <main className="w-full">
            <Navbar/>
            <div className="px-4">{children}</div>
          </main>
          </CoursesProvider>
      </ThemeProvider>
    </SidebarProvider>
  );
}
